import {parentPort,workerData} from 'node:worker_threads';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import {dirname,join} from 'node:path';import {PNG} from 'pngjs';import jpeg from 'jpeg-js';
const raw=Buffer.from(workerData),limit=16000000;let orientation=1;
function exif(bytes:Buffer){let start=bytes.subarray(0,6).equals(Buffer.from('Exif\0\0'))?6:0;const data=bytes.subarray(start);if(data.length<8)return;const little=data.toString('ascii',0,2)==='II',u16=(p:number)=>little?data.readUInt16LE(p):data.readUInt16BE(p),u32=(p:number)=>little?data.readUInt32LE(p):data.readUInt32BE(p);try{const offset=u32(4),count=u16(offset);for(let i=0;i<count;i++){const p=offset+2+i*12;if(u16(p)===274){const value=u16(p+8);if(value>=1&&value<=8)orientation=value;return;}}}catch{}}
function dimensions(width:number,height:number){if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width*height>limit)throw Error('图片尺寸超限');}
try{
 let image:{width:number;height:number;data:Uint8Array|Uint8ClampedArray};
 if(raw.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))){dimensions(raw.readUInt32BE(16),raw.readUInt32BE(20));for(let p=8;p+12<=raw.length;){const size=raw.readUInt32BE(p),type=raw.toString('ascii',p+4,p+8);if(type==='acTL')throw Error('不支持动画');if(type==='eXIf')exif(raw.subarray(p+8,p+8+size));p+=size+12;}image=PNG.sync.read(raw);}
 else if(raw[0]===255&&raw[1]===216){for(let p=2;p+4<raw.length;){if(raw[p]!==255){p++;continue;}const marker=raw[p+1];if(marker===218)break;const size=raw.readUInt16BE(p+2);if(size<2)break;if(marker===225)exif(raw.subarray(p+4,p+2+size));p+=size+2;}image=jpeg.decode(raw,{useTArray:true,maxResolutionInMP:16,maxMemoryUsageInMB:96});dimensions(image.width,image.height);}
 else if(raw.toString('ascii',0,4)==='RIFF'&&raw.toString('ascii',8,12)==='WEBP'){
  let width=0,height=0;for(let p=12;p+8<=raw.length;){const type=raw.toString('ascii',p,p+4),size=raw.readUInt32LE(p+4),chunk=raw.subarray(p+8,p+8+size);if(type==='ANIM'||type==='ANMF')throw Error('不支持动画');if(type==='EXIF')exif(chunk);if(type==='VP8X'){if(chunk[0]&2)throw Error('不支持动画');width=1+chunk.readUIntLE(4,3);height=1+chunk.readUIntLE(7,3);}else if(type==='VP8 '&&chunk.length>=10){width=chunk.readUInt16LE(6)&16383;height=chunk.readUInt16LE(8)&16383;}else if(type==='VP8L'&&chunk.length>=5){const bits=chunk.readUInt32LE(1);width=(bits&16383)+1;height=((bits>>>14)&16383)+1;}p+=8+size+(size%2);}
  dimensions(width,height);const require=createRequire(import.meta.url),moduleFile=require.resolve('@jsquash/webp/decode.js'),{default:decode,init}=await import('@jsquash/webp/decode.js');await init(await WebAssembly.compile(readFileSync(join(dirname(moduleFile),'codec/dec/webp_dec.wasm'))));image=await decode(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength) as ArrayBuffer);dimensions(image.width,image.height);
 }else throw Error('不支持的格式');
 const swapped=orientation>=5,width=swapped?image.height:image.width,height=swapped?image.width:image.height,side=Math.min(width,height),left=(width-side)/2,top=(height-side)/2,out=new PNG({width:256,height:256});
 const source=(x:number,y:number)=>{let sx=x,sy=y;switch(orientation){case 2:sx=image.width-1-x;break;case 3:sx=image.width-1-x;sy=image.height-1-y;break;case 4:sy=image.height-1-y;break;case 5:sx=y;sy=x;break;case 6:sx=y;sy=image.height-1-x;break;case 7:sx=image.width-1-y;sy=image.height-1-x;break;case 8:sx=image.width-1-y;sy=x;break;}return (Math.max(0,Math.min(image.height-1,sy))*image.width+Math.max(0,Math.min(image.width-1,sx)))*4;};
 for(let y=0;y<256;y++)for(let x=0;x<256;x++){const px=Math.max(0,Math.min(width-1,left+(x+.5)*side/256-.5)),py=Math.max(0,Math.min(height-1,top+(y+.5)*side/256-.5)),x0=Math.floor(px),y0=Math.floor(py),dx=px-x0,dy=py-y0,indices=[source(x0,y0),source(Math.min(width-1,x0+1),y0),source(x0,Math.min(height-1,y0+1)),source(Math.min(width-1,x0+1),Math.min(height-1,y0+1))],weights=[(1-dx)*(1-dy),dx*(1-dy),(1-dx)*dy,dx*dy],offset=(y*256+x)*4;for(let c=0;c<3;c++){let value=0;for(let i=0;i<4;i++){const alpha=image.data[indices[i]+3]/255;value+=(image.data[indices[i]+c]*alpha+255*(1-alpha))*weights[i];}out.data[offset+c]=Math.round(value);}out.data[offset+3]=255;}
 parentPort!.postMessage({png:PNG.sync.write(out,{deflateLevel:9})});
}catch{parentPort!.postMessage({error:'invalid_image'});}
