// @ts-nocheck
import './motion';
import './surfaces';
import '../compat/lingxi-design';
import '../compat/dialogs';
export function mountPreview(root,options={}) {
const abort=new AbortController(),signal=abort.signal;const cleanups=[];
root.classList.add('lingxi-preview');
const D=window.LingxiDesign,R=window.WorkbenchReact,e=D.escape,q=s=>root.querySelector(s);
const notify=(message,kind='info')=>R.toast(q('#preview-toast'),message,{kind});
const button=(label,action,kind='secondary')=>`<button type="button" class="onboarding-action ${kind}" data-action="${action}">${label}</button>`;
const field=(label,value='',type='text')=>`<label class="control-field">${label}<input type="${type}" value="${e(value)}" autocomplete="off"></label>`;
const table=(heads,rows)=>`<div class="preview-table-scroll"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const section=(id,n,title,lead,body)=>`<section class="preview-section" id="${id}" data-preview-section><small class="preview-eyebrow">${n} — ${title}</small><h2>${title}</h2><p class="preview-lead">${lead}</p>${body}</section>`;
const card=(title,body)=>`<article class="preview-card"><h3>${title}</h3>${body}</article>`;
const modules=['总览','项目与待办','总结','热点','记账','用量','提示词','技能'];
const swatches=[['--accent','主题蓝','选中、链接与焦点'],['--ink','正文色','文字与主要操作'],['--lingxi-shell','框架','顶栏与侧栏'],['--lingxi-body','画布','主体内容'],['--surface','表面','卡片与弹窗'],['--line','边界','分隔与控件轮廓'],['--ink-2','次要文字','说明与元数据'],['--accent-soft','选中表面','轻筛选与反馈']];
const types=[['display',72,500,1.12,'灵犀工作坊'],['section',48,500,1.2,'颜色、字体与交互'],['heading',28,500,1.3,'让工作有清楚的结构'],['title',20,600,1.4,'本周工作'],['body',16,400,1.6,'从项目、待办到用量，每一项信息都有明确的位置。'],['utility',14,400,1.5,'模型、时间范围与资料位置'],['caption',12,400,1.5,'最近更新 · 仅用于演示']];
let html=`<header class="preview-top"><a class="preview-brand" href="index.html" data-return><img src="assets/lingxi-logo.svg" alt=""><span>灵犀工作坊</span></a><nav aria-label="设计预览"><a href="#palette">颜色</a><a href="#typography">字体</a><a href="#buttons">组件</a><a href="#cards">卡片</a></nav><div class="preview-top-actions"><a href="/design.md">规范 ↗</a><button data-theme-toggle type="button">深色</button></div></header><main class="preview-content"><section class="preview-hero" id="overview" data-preview-section><div class="preview-hero-copy" data-motion-row><small class="preview-eyebrow">DESIGN SYSTEM · ${__LINGXI_VERSION__}</small><h1>灵犀工作坊<br>设计系统</h1><p>清楚的层级、稳定的布局、可退出的交互。<br>工作坊的颜色、字体、实际控件与代表性业务组合。</p><div class="preview-actions"><a class="onboarding-action" href="/design.md">阅读规范</a><a class="onboarding-action secondary" href="index.html" data-return>返回工作坊</a></div><small>全部数据为合成演示，不读取或修改实际 Profile。</small></div><aside class="preview-code" data-motion-row><header><span>design.md</span><button type="button" data-copy-code aria-label="复制设计令牌">复制</button></header><pre><code data-design-code>正在读取设计令牌…</code></pre><footer><a href="/design.md">阅读完整规范 ↗</a></footer></aside></section>`;
html+=section('palette','01','Color Palette','同一套角色贯穿浅深主题。',`<div class="preview-palette">${swatches.map(([token,label,role])=>`<article class="preview-swatch"><div style="background:var(${token})"></div><section><strong>${label}</strong><code data-color="${token}"></code><p>${role}</p></section></article>`).join('')}</div><div class="preview-state-row"><span class="preview-success">✓ 成功 · #16834b</span><span class="preview-danger">× 错误 · #e5484d</span><span class="preview-warning">! 警告 · #b77913</span><span>i 信息 · #2563eb</span></div>`);
html+=section('typography','02','Typography','系统无衬线负责阅读与操作，数字使用等宽位；书法字体只用于品牌。',types.map(([token,size,weight,line,text])=>`<div class="preview-type-row"><div><code>${token}</code><small>${size}px · ${weight} · ${line}</small></div><p style="--sample-size:${size}px;font-weight:${weight};line-height:${line}">${text}</p></div>`).join(''));
html+=section('buttons','03','Buttons & States','操作、选择与反馈使用实际集成组件。',`<div class="preview-grid four">${card('主要操作',button('确认保存','success',''))}${card('次要操作',button('取消','info'))}${card('轻操作',button('查看说明 ↗','info','quiet'))}${card('禁用','<button class="onboarding-action secondary" disabled>不可操作</button>')}</div><div class="preview-grid four">${card('SquishSwitch','<div data-switch></div>')}${card('JellyRadio','<div data-radio></div>')}${card('SlideCommit','<div data-commit></div>')}${card('LatticeLoader / WakeSlider','<div data-loader></div><div data-progress></div>')}</div><div class="preview-state-row"><span>未知 <b>--</b></span><span>明确为零 <b>0</b></span><span class="preview-success">✓ 已保存</span><span class="preview-danger">× 读取失败</span><span class="preview-warning">! 部分覆盖</span></div><div class="preview-actions">${['success','error','info','warning'].map((kind,i)=>button(['成功通知','错误通知','普通信息','警告通知'][i],kind)).join('')}</div>`);
html+=section('cards','04','Cards & Containers','轻边界、明确层级。金额与账户读取独立更新。',`<div class="preview-grid three">${card('本周工作','<strong class="preview-number">3 <small>个项目</small></strong><p>8 项待办，2 项已完成。</p><label class="preview-task"><input type="checkbox"> 整理资料</label><label class="preview-task"><input type="checkbox" checked> 核对需求清单</label>')}${card('本地 Token','<strong class="preview-number">184,200</strong><p>七天 · 演示</p><svg class="preview-trend" viewBox="0 0 320 130" role="img" aria-label="七天合成Token趋势"><g stroke="var(--line)"><path d="M0 30H320M0 70H320M0 110H320"/></g><path d="M0 104L50 68L100 84L150 38L200 60L250 18L320 44" fill="none" stroke="var(--accent)" stroke-width="3" stroke-linejoin="round"/></svg>')}${card('API 参考等价值','<div data-value-switch></div><div class="preview-money"><span>USD <strong data-usd>--</strong></span><span>CNY <strong data-cny>--</strong></span></div><p>依据本地用量与历史价格计算。</p>'+button('查看价格与汇率 ↗','prices','quiet'))}</div><div class="preview-grid two">${card('Codex 账户','<div class="preview-quota"><svg viewBox="0 0 100 100" aria-label="演示额度"><circle cx="50" cy="50" r="40" fill="none" stroke="var(--line)" stroke-width="8"/><circle data-quota-ring cx="50" cy="50" r="40" fill="none" stroke="var(--accent)" stroke-width="8" stroke-dasharray="0 252" transform="rotate(-90 50 50)"/></svg><div><small>5 小时额度</small><strong data-quota>--</strong><small data-account-state>尚未读取</small></div></div><div data-batteries></div><div class="preview-actions">'+button('模拟读取','account')+button('连接窗口','authorization')+'</div>')}${card('Profile','<div class="onboarding-cards"><article class="onboarding-card" data-selected="true"><h3>演示工作空间</h3><p>工作内容与设置独立保存。</p></article><article class="onboarding-card"><h3>另一个 Profile</h3><p>选择已有资料或创建新的空间。</p></article></div>'+button('选择工作空间','profile'))}</div><article class="preview-card"><div class="preview-module-tabs" role="tablist" aria-label="业务模块演示">${modules.map((m,i)=>`<button role="tab" aria-selected="${i===0}" data-demo-module="${m}">${m}</button>`).join('')}</div><div data-module-content></div></article>`);
html+=section('forms','05','Forms & Windows','输入、错误和操作分区；窗口尺寸随任务变化，关闭逻辑保持一致。',`<div class="preview-grid two">${card('输入与选择',field('用户名','演示用户')+'<label class="control-field">来源<select><option>Codex</option><option>ZCode</option><option>DeepSeek Harness</option></select></label><label class="control-field">说明<textarea rows="3" placeholder="保留你的原始输入"></textarea></label><label class="control-field">只读信息<input value="当前 Profile" disabled></label>')}${card('设置与错误','<div class="preview-setting-row"><span>字号</span><div data-font></div></div><div class="preview-setting-row"><span>亮度</span><div data-brightness></div></div><label class="control-field">名称<input aria-invalid="true" aria-describedby="preview-input-error" value=""></label><p class="preview-danger" id="preview-input-error">请输入名称，原输入保留。</p>')}</div><div class="preview-grid four preview-windows">${[['small','360px','简单信息'],['medium','560px','确认与授权'],['large','800px','长内容与表格'],['settings','1040px','复杂设置']].map(([size,width,label])=>card(label,`<div class="preview-window-silhouette"><i></i><i></i><i></i></div><code>${size} · ${width}</code>`+button('打开窗口',size))).join('')}</div>`);
html+=section('spacing','06','Spacing','以 4px 为基础，界面内容紧凑，展陈章节有充分留白。',`<div class="preview-spacing">${[4,8,12,16,24,32,48,96].map(n=>`<div><code>${n}px</code><span style="width:${n}px"></span></div>`).join('')}</div>`);
html+=section('radius','07','Border Radius','控件、卡片与窗口各有稳定的形状。',`<div class="preview-radius">${[[6,'标记'],[10,'输入与按钮'],[16,'内容卡片'],[24,'引导与窗口'],[999,'日期与筛选']].map(([n,label])=>`<article><div style="border-radius:${n}px">${n===999?'∞':n}</div><code>${label}</code></article>`).join('')}</div>`);
html+=section('depth','08','Elevation & Depth','表面和边界表达层级，浮层使用轻阴影。',`<div class="preview-depth">${['画布','卡片','菜单','窗口'].map((name,i)=>`<article><div>${name}</div><code>Level ${i}</code></article>`).join('')}</div>`);
html+=section('responsive','09','Responsive Behavior','浅深共用结构，不同窗口下操作和退出始终可达。',table(['宽度','展示策略'],[['≥1024px','色板多列，卡片2–3列，字体元数据与样例并排'],['720–1023px','卡片2列，外边距24px'],['<720px','单列，边距16px，章节48px'],['320 / 390px','表格自身滚动，窗口底部按钮可达']])+`<div class="preview-grid two">${card('动作与键盘','<p>Tab 显示焦点；Esc 关闭窗口并返回触发控件。菜单互斥，侧栏只在240px与64px之间切换。</p><label class="preview-task"><input type="checkbox" data-reduced> 减少动态效果</label>')}${card('主题与信息','<p>主题切换保持内容与位置。未知值不参与数字动画，失败保留已读取结果。</p><p>✓ 成功　× 错误　i 信息　! 警告</p>')}</div>`);
html+='</main><footer class="preview-footer"><span>灵犀工作坊 · 设计系统</span><a href="https://github.com/VoltAgent/awesome-design-md" target="_blank" rel="noopener">展示结构参考 awesome-design-md ↗</a></footer><div id="preview-toast"></div>';
root.innerHTML=html;
function paintTheme(){const styles=getComputedStyle(document.documentElement);root.querySelectorAll('[data-color]').forEach(n=>n.textContent=styles.getPropertyValue(n.dataset.color).trim());q('[data-theme-toggle]').textContent=document.documentElement.dataset.theme==='dark'?'浅色':'深色';}
if(options.dark!==undefined)document.documentElement.dataset.theme=options.dark?'dark':'light';paintTheme();
fetch('/design.md',{signal,redirect:'error'}).then(response=>{if(!response.ok)throw Error('规范不可用');return response.text();}).then(text=>{if(signal.aborted)return;const yaml=text.match(/^---[\s\S]*?\n---/);q('[data-design-code]').textContent=yaml?yaml[0]:text;q('[data-copy-code]').onclick=()=>navigator.clipboard.writeText(q('[data-design-code]').textContent).then(()=>notify('已复制设计令牌','success')).catch(()=>notify('复制失败','error'));}).catch(error=>{if(!signal.aborted)q('[data-design-code]').textContent=error.message;});
q('[data-theme-toggle]').onclick=event=>{const commit=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';paintTheme();};if(document.startViewTransition&&document.documentElement.dataset.motion!=='reduced'){const t=document.startViewTransition(commit),rect=event.currentTarget.getBoundingClientRect(),x=rect.left+rect.width/2,y=rect.top+rect.height/2,r=Math.hypot(Math.max(x,innerWidth-x),Math.max(y,innerHeight-y));t.ready.then(()=>document.documentElement.animate({clipPath:[`circle(0px at ${x}px ${y}px)`,`circle(${r}px at ${x}px ${y}px)`]},{duration:650,easing:'cubic-bezier(.22,1,.36,1)',pseudoElement:'::view-transition-new(root)'}));}else commit();};
try{const route=sessionStorage.getItem('lingxi-last-work-route');if(route&&/^#\/(overview|projects|summary|news|finance|usage|prompts|skills)/.test(route))root.querySelectorAll('[data-return]').forEach(n=>n.href='index.html'+route);}catch{}
let switched=true,selected='daily',committed=false,valueEnabled=false,accountReady=false;
function paintSwitch(){R.squishSwitch(q('[data-switch]'),{checked:switched,ariaLabel:'演示自动同步',onChange:v=>{switched=v;paintSwitch();}});}paintSwitch();
function paintRadio(){R.radio(q('[data-radio]'),{items:[{value:'daily',label:'每日'},{value:'weekly',label:'每周'},{value:'all',label:'累计'}],value:selected,onChange:v=>{selected=v;paintRadio();}});}paintRadio();
function paintCommit(){R.slideCommit(q('[data-commit]'),{enabled:committed,onConfirm:async()=>{committed=!committed;paintCommit();return true;}});}paintCommit();
const disposeLoader=R.loader(q('[data-loader]'),'正在读取 · 演示');R.progress(q('[data-progress]'),64);
function paintValue(){R.slideCommit(q('[data-value-switch]'),{enabled:valueEnabled,compact:true,onConfirm:async()=>{valueEnabled=!valueEnabled;paintValue();return true;}});q('[data-usd]').textContent=valueEnabled?'128.00':'--';q('[data-cny]').textContent=valueEnabled?'896.00':'--';}paintValue();
function paintAccount(){q('[data-quota]').textContent=accountReady?'74.2%':'--';q('[data-account-state]').textContent=accountReady?'演示凭据已读取':'尚未读取';q('[data-quota-ring]').setAttribute('stroke-dasharray',accountReady?'187 252':'0 252');D.resetBatteries(q('[data-batteries]'),accountReady?{availableCount:2,credits:[{grantedAt:Date.now()/1000-86400,expiresAt:Date.now()/1000+86400},{expiresAt:null}]}:null);}paintAccount();
R.scrubField(q('[data-font]'),{ariaLabel:'界面字号',value:14,min:12,max:18,step:2,onChange:v=>q('[data-module-content]').style.fontSize=v+'px'});R.scrubField(q('[data-brightness]'),{ariaLabel:'界面亮度',value:100,min:85,max:110,step:1,onChange:v=>q('[data-module-content]').style.filter='brightness('+v/100+')'});
const moduleBodies={'总览':'<div class="preview-metrics"><div><small>进行中项目</small><strong>3</strong></div><div><small>待完成任务</small><strong>8</strong></div><div><small>本月支出</small><strong>¥128.30</strong></div></div>','项目与待办':'<h3>演示项目</h3><label class="preview-task"><input type="checkbox"> 核对项目资料</label><label class="preview-task"><input type="checkbox" checked> 完成需求清单</label>','总结':'<h3>本月总结</h3><textarea rows="4" aria-label="演示总结">已完成两项任务，下一步整理资料。</textarea>','热点':'<h3>今日热点 · 演示</h3><p>人工智能工具的工作方式</p><p>本地资料与个人工作流</p>','记账':table(['日期','说明','收支','金额'],[['10/09','演示收入','收入','¥120.00'],['10/08','演示支出','支出','¥12.30']]),'用量':table(['时间','来源','模型','Token','状态'],[['10:24','Codex','演示模型 A','1,240','已核验'],['10:22','Harness','未返回','--','缺少分项']]),'提示词':'<article class="wb-library-card"><h3>会议记录整理</h3><p>按议题、结论和待办组织笔记。</p><small>Markdown</small></article>','技能':'<article class="wb-library-card"><h3>资料整理</h3><p>只读已登记的技能说明。</p><small>本机来源</small></article>'};q('[data-module-content]').innerHTML=moduleBodies['总览'];
function openWindow(size){const content=size==='large'?table(['项目','状态','说明'],Array.from({length:24},(_,i)=>['演示项目 '+(i+1),'已核验','长内容可滚动，底部操作保持可见'])):size==='settings'?'<div class="preview-settings"><nav>常规<br>外观<br>用量<br>供应商<br>数据与备份<br>关于</nav><section><h3>外观</h3>'+field('工作坊名称','演示工作坊')+field('字号','14','number')+'</section></div>':size==='small'?'<p>这是一条简短信息，阅读后即可关闭。</p>':'<p>保存当前设置，保留已有的工作内容。</p>'+field('名称','演示设置');window.WorkbenchDialogs.open({title:size==='small'?'信息':size==='settings'?'设置中心':size==='large'?'数据详情':'确认保存',size,body:content,actions:[{id:'cancel',label:'取消 / 返回'},{id:'confirm',label:size==='small'?'知道了':'保存（演示）',kind:'primary',onClick:()=>{notify('演示操作完成，未写入实际资料','success');return true;}}]});}
root.addEventListener('click',event=>{const module=event.target.closest('[data-demo-module]');if(module){root.querySelectorAll('[data-demo-module]').forEach(n=>n.setAttribute('aria-selected',String(n===module)));q('[data-module-content]').innerHTML=moduleBodies[module.dataset.demoModule];return;}const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;if(['small','medium','large','settings'].includes(action)){openWindow(action);return;}if(action==='account'){accountReady=!accountReady;paintAccount();return;}if(action==='authorization'){window.WorkbenchDialogs.open({title:'连接 Codex · 演示',size:'medium',body:'<p>授权读取本机已有凭据，用于查询额度、Credit与重置卡。</p><p>此演示不读取任何实际凭据。</p>',actions:[{label:'取消'},{label:'授权读取（演示）',kind:'primary',onClick:()=>{accountReady=true;paintAccount();notify('演示授权完成','success');return true;}}]});return;}if(action==='profile'){window.WorkbenchDialogs.open({title:'选择工作空间',size:'large',body:q('.onboarding-cards').outerHTML,actions:[{label:'返回'},{label:'选择（演示）',kind:'primary',onClick:()=>{notify('已选择演示工作空间','success');return true;}}]});return;}if(action==='prices'){window.WorkbenchDialogs.open({title:'价格与汇率 · 演示',size:'large',body:table(['日期','模型','输入 / 百万','输出 / 百万'],[['2026-10-09','演示模型 A','$1.00','$4.00']])+'<p>USD/CNY 7.00，仅用于展示，非实际汇率。</p>',actions:[{label:'关闭'}]});return;}notify({success:'演示保存成功',error:'Cannot read data · 演示失败，原输入保留',warning:'部分记录尚未核验',info:'这是一条演示信息'}[action]||'演示信息',action);},{signal});
q('[data-reduced]').onchange=event=>document.documentElement.dataset.motion=event.target.checked?'reduced':'full';
const stopReveal=window.WorkbenchMotion?.rows(root,true);
window.lingxiPreviewCoverage={version:__LINGXI_VERSION__,sections:['overview','palette','typography','buttons','cards','forms','spacing','radius','depth','responsive'],businessModules:8,data:'synthetic-only',persistentTableOfContents:false};
return ()=>{abort.abort();stopReveal?.();disposeLoader();R.cleanup(root);};

}
const standalone=document.getElementById("design-preview");if(standalone){const dispose=mountPreview(standalone,{dark:location.pathname.includes("preview-dark")});window.WorkbenchWindow?.mount(standalone.querySelector(".preview-top"));window.addEventListener("pagehide",dispose,{once:true});}
