// @ts-nocheck
import '../compat/lingxi-design';
import '../compat/usage-charts';
import '../compat/usage-accounts';
const D=window.LingxiDesign,C=window.usageCharts,R=window.WorkbenchReact,e=D.escape;
const sections=[];
const button=(label,action=label)=>`<button type="button" class="btn ghost" data-demo-action="${e(action)}">${e(label)}</button>`;
const table=(heads,rows)=>`<div class="preview-table-scroll"><table class="preview-table"><thead><tr>${heads.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(value=>`<td>${e(value)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const panel=(title,content)=>`<article class="preview-panel"><h3>${e(title)}</h3>${content}</article>`;
const field=(label,value='',type='text')=>`<label class="control-field">${e(label)}<input type="${type}" value="${e(value)}" aria-label="${e(label)}" ${type==='password'?'autocomplete="off"':''}></label>`;
const metrics=(values)=>`<div class="preview-metrics">${values.map(([label,value])=>`<article class="preview-panel"><small>${e(label)}</small><strong>${e(value)}</strong></article>`).join('')}</div>`;
function section(id,title,description,body){sections.push({id,title,description});return `<section id="${id}" data-preview-section><div class="preview-section-heading"><h2>${e(title)}</h2><p>${e(description)}</p></div>${body}</section>`;}
const rows=[{date:'2026-10-02',total:14000,models:[]},{date:'2026-10-03',total:24000,models:[]},{date:'2026-10-04',total:9000,models:[]},{date:'2026-10-05',total:37000,models:[]},{date:'2026-10-06',total:42000,models:[]},{date:'2026-10-07',total:31000,models:[]},{date:'2026-10-08',total:18000,models:[]}];
const trend=()=>`<div class="preview-chart usage-charts" data-metric="token">${C.trend(rows)}</div>`;
const quota=(slot,label,remaining,minutes)=>window.usageAccounts.quotaPreview({slot,label,remaining,minutes,reset:Date.now()+minutes*30000});
let html=section('framework','应用框架与导航','顶栏固定；模块标签栏固定；主体滚动；收起保留图标。',`<div class="control-actions">${button('展开 / 收起图标栏','sidebar')}</div><div class="preview-shell" data-demo-shell><header>←　→　☷　　文件　编辑　视图　帮助　　◐</header><aside><div class="onboarding-brand"><img src="assets/lingxi-logo.svg" alt="灵犀"><span>灵犀</span></div>${['总览','项目与待办','用量监测','提示词','技能'].map((name,i)=>`<button class="preview-navigation ${i===2?'selected':''}" data-demo-module="${name}"><span aria-hidden="true">${['⌂','□','◔','≡','◇'][i]}</span><span data-demo-nav-label>${name}</span></button>`).join('')}<div class="preview-user">我 <span data-demo-nav-label>演示用户</span></div></aside><div class="preview-shell-body"><div class="preview-tabs" data-demo-module-label>Codex　 ZCode　 DeepSeek Harness　 API供应商</div><div class="preview-demo-content"><h3>工作区域保持独立滚动</h3><p class="meta">卡片、表格、编辑器和图表共享同一套令牌。</p>${metrics([['范围 Token','184,200'],['请求数','128']])}</div></div></div>`);
html+=section('colors','颜色与语义','颜色负责动作、层级或数据含义，不能只有漂亮色块。',`<div class="preview-palette">${[['框架','--lingxi-shell'],['画布','--lingxi-body'],['表面','--surface'],['正文','--ink'],['次级','--ink-2'],['边界','--line'],['强调','--accent']].map(([name,token])=>`<article><div data-token-color="${token}"></div><strong>${name}</strong><code data-token-value="${token}"></code></article>`).join('')}</div><div class="preview-semantic"><span>● 选择 / 动作</span><span class="preview-success">● 已保存 / 已开启</span><span class="preview-warning">● 部分覆盖</span><span class="preview-danger">● 无法完成</span></div>`);
html+=section('typography','字体、数字与文案','品牌书法 / 中文工作字体 / 等宽代码；数字使用等宽数字。',`<div class="preview-type">${panel('标题与正文','<h2>整理你的工作</h2><p>标签说明含义，正文解释下一步；未知值保留为 --。</p><small>说明文字也要保持可读对比。</small>')}${panel('数据与代码','<strong>2,019,777,301</strong><p>累计 Token · 演示</p><code>{{topic}} / input_tokens / ¥ 128.30</code>')}</div>${table(['角色','默认大小','字重','用途'],[['品牌','28px','400','Logo旁字标'],['页面','24px','500','页面标题'],['分区','18px','500','工作分区'],['正文','14px','400','标签与工作内容'],['说明','12–13px','400','时间、范围与辅助说明']])}`);
html+=section('spacing','间距、容器与形状','4px 节拍；内容紧凑，分区明确；卡片 16px、输入 12px。',`<div class="preview-spacing">${[4,8,12,16,24,32].map(value=>`<article><div style="height:${value}px"></div><code>${value}px</code></article>`).join('')}</div><div class="preview-demo-grid">${panel('普通卡片','<p>同级 16–20px，标题与内容 12–16px。</p>')}${panel('浮层与弹窗',`<p>浮层用柔和投影，内容受视口限制。</p>${button('打开标准弹窗','dialog')}`)}</div>`);
html+=section('controls','实际组件与输入','展示实际集成控件，保留键盘与触摸交互。',`<div class="preview-demo-grid">${panel('布尔与互斥','<div class="preview-control-row"><label>自动同步</label><span data-demo-switch></span></div><div data-demo-radio></div>')}${panel('字号与亮度','<div class="preview-control-row"><label>界面字号</label><span data-demo-font></span></div><div class="preview-control-row"><label>界面亮度</label><span data-demo-brightness></span></div><p class="meta" data-demo-brightness-value>100% · 仅预览当前控件区域</p>')}${panel('输入与选择',`<div class="preview-form-grid">${field('名称','演示工作空间')}${field('API Key','demo-placeholder','password')}<label class="control-field">模型<select><option>全部模型</option><option>演示模型 A</option><option>演示模型 B</option></select></label><label class="control-field">备注<textarea rows="3">保留草稿与原文。</textarea></label></div>`)}${panel('等待与准备','<div data-demo-loader></div><div data-demo-progress></div><p class="meta">只读进度，不展示虚构倒计时。</p>')}</div>`);
html+=section('states','默认、悬停、焦点与异常','同一控件完整展示；空、等待、失败、未知不能混为一谈。',`<div class="control-actions"><button class="btn">主动作</button>${button('次动作')}<button class="btn" disabled>正在保存</button><button class="btn ghost" disabled>不可操作</button><a href="#accessibility">键盘与焦点 ↗</a></div><div class="preview-state-grid">${panel('尚未连接','<strong>--</strong><p class="meta">先授权读取本机凭据。</p>')}${panel('确认没有记录','<strong>0</strong><p class="meta">没有实际交易，可导入账单。</p>')}${panel('部分覆盖','<strong>已核验 92 / 100</strong><p class="preview-warning">金额只包含已核验部分。</p>')}${panel('读取失败',`<p class="preview-danger" role="alert">暂时无法读取，原结果保留。</p>${button('重试')}`)}${panel('保存冲突',`<p>新编辑保留，请比较后重试。</p>${button('查看冲突','dialog')}`)}${panel('输入错误','<label class="control-field">用户名<input aria-invalid="true" aria-describedby="demo-invalid-name" value=""></label><p id="demo-invalid-name" class="preview-danger">请输入用户名。</p>')}</div>`);
html+=section('onboarding','开屏与完整引导','Logo → Profile → 身份 → 监测 → 本机凭据 → 供应商。',`<div class="preview-step-list">${['Logo','选择 Profile','用户名与头像','Agent 监测','授权本机凭据','API供应商','工作台'].map((name,i)=>`<span><small>${i+1}</small>${name}</span>`).join('')}</div><div class="preview-demo-grid">${panel('创建身份','<div data-demo-identity></div>')}${panel('连接来源',`<div class="onboarding-cards">${['Codex','ZCode','DeepSeek Harness'].map(name=>`<article class="onboarding-card"><h3>${name}</h3><p>只读本机已存在的日志</p>${field('日志位置','演示日志目录')}</article>`).join('')}</div><div class="control-actions">${button('上一步')}${button('稍后设置')}${button('继续')}</div>`)}</div>`);
html+=section('profile','Profile 卡片与个人菜单','首次引导、切换实例、数据设置采用同一视觉。',`<div class="onboarding-cards lingxi-profile-cards"><article class="onboarding-card" data-selected="true"><h2>当前 Profile</h2><p>演示工作空间 / profile</p><small>工作内容、设置和凭据彼此隔离。</small></article><article class="onboarding-card"><h2>选择或创建 Profile</h2><p>打开已有资料，或在空文件夹创建。</p>${button('选择文件夹','profile')}</article></div><div class="preview-demo-grid">${panel('网页连接',`${field('服务地址','http://localhost:8765')}<div class="control-actions">${button('连接实例','profile')}</div>`)}${panel('个人入口',`<div class="preview-profile-popover lingxi-profile-popover is-open">${D.profileMenuMarkup('演示用户')}</div><div class="preview-user-anchor">我　演示用户</div>`)}</div>`);
html+=section('account','Codex 账户的完整状态','额度与参考价值分别控制；金额不依赖凭据。',`<div class="control-actions">${button('模拟读取凭据','account')}<span class="meta" data-demo-account-state>尚未读取</span></div><div class="lingxi-codex-account"><div class="lingxi-quota-stack" data-demo-quotas></div><div class="lingxi-account-details"><section class="lingxi-value-card"><div class="agent-value-panel"><header><h3>API等效参考价值</h3><div class="agent-value-commit"><div data-demo-value-slide></div></div></header><div class="agent-value-line"><div class="agent-value-amounts"><span class="agent-value-usd">USD <strong data-demo-usd>--</strong></span><span class="agent-value-cny">CNY <strong data-demo-cny>--</strong></span></div><a href="#prices" class="agent-value-source">查看价格与汇率 ↗</a></div></div></section><section class="lingxi-credit-single"><h4>剩余 Credit</h4><strong data-demo-credit>--</strong></section><section class="lingxi-reset-card" data-demo-batteries></section></div></div><p class="meta">保持参考价值开启，再切换凭据状态：开关与金额应继续存在。</p>`);
html+=section('usage','用量筛选、摘要与明细','四种来源、独立筛选、稳定双币种、确认与缺口。',`<div class="preview-tabs">Codex　 ZCode　 DeepSeek Harness　 API供应商</div>${metrics([['累计 Token','184,200'],['单日峰值','42,000'],['当前连续','7 天'],['最长连续','18 天']])}<div class="preview-filter-grid">${['时间范围','来源','服务商','工作区','模型'].map(label=>`<label class="control-field">${label}<select><option>全部</option><option>演示选项</option></select></label>`).join('')}</div>${table(['时间','来源','实际模型','Token','状态','耗时'],[['10:24','Codex','演示模型 A','1,240','已核验','1.2s'],['10:23','ZCode','演示模型 B','860','已核验','0.9s'],['10:22','Harness','未返回','--','缺少分项','--']])}`);
html+=section('charts','趋势、分布与统一提示','图表有范围、方向、空态、键盘与触摸说明。',trend()+`<div class="preview-demo-grid">${panel('模型分布',`<div class="preview-demo-donut"><span>184,200<br><small>Token · 演示</small></span></div><ul class="preview-legend"><li>● 演示模型 A　60%</li><li>● 演示模型 B　30%</li><li>● 其他　10%</li></ul>`)}${panel('固定宽度提示',`<div class="usage-tooltip preview-tooltip">${D.tooltipMarkup({primary:'42,000 Token',date:'2026年10月6日 · 演示',rows:[{label:'演示模型 A',value:'28,400',color:'#2563eb'},{label:'很长的模型分类用于确认省略效果',value:'13,600',color:'#e6a544'}]})}</div>`)}</div>`);
html+=section('overview','总览','工作摘要、最近活动与模块入口。',metrics([['进行中项目','3'],['待完成任务','8'],['本月支出','¥ 128.30']])+`<div class="preview-demo-grid">${panel('正在进行',table(['项目','状态','任务'],[['演示项目 A','进行中','3 / 5'],['演示项目 B','计划中','0 / 3']]))}${panel('最近活动','<ul class="preview-activity"><li><strong>保存个人资料</strong><small>今天 10:24</small></li><li><strong>整理提示词</strong><small>今天 10:10</small></li><li><strong>完成待办</strong><small>昨天 18:32</small></li></ul>')}</div>`);
html+=section('projects','项目、待办与通知识别','卡片、完成状态、任务编辑、识别预览和删除保护。',`<div class="control-actions">${button('新增项目','project')}${button('新增待办','task')}${button('识别通知','notification')}</div><div class="preview-demo-grid">${panel('演示项目 A','<span class="preview-badge">进行中</span><p>准备本周资料与汇报。</p><label class="preview-task"><input type="checkbox"> 整理资料 <small>今天</small></label><label class="preview-task"><input type="checkbox" checked> 核对清单 <small>已完成</small></label>')}${panel('演示项目 B','<span class="preview-badge">计划中</span><p>新的工作空间。</p><div class="control-empty">尚无待办，添加一项开始。</div>')}</div>`);
html+=section('summary','月度总结','统计、项目分类、正文、保存与草稿。',metrics([['完成任务','18'],['进行中项目','3'],['新增记录','12']])+panel('总结正文','<label class="control-field">月份<input type="month" value="2026-10"></label><label class="control-field">本月总结<textarea rows="5">演示：完成资料整理，下一步补充验证。</textarea></label><div class="control-actions">'+button('保存总结')+button('查看统计')+'</div>'));
html+=section('news','热点与外部来源','标题、来源、日期、摘要与局部失败。',`<div class="control-actions">${button('刷新热点')}</div><div class="preview-demo-grid">${panel('演示文章标题','<span class="preview-badge">公开来源</span><p>摘要只用于展示卡片的文字密度。</p><small>2026-10-09 · 演示</small>')}${panel('某来源暂不可用',`<p class="preview-danger">其他来源内容继续保留。</p>${button('重试来源')}`)}</div>`);
html+=section('finance','记账：摘要、趋势、分类与交易','金额对齐；收入 / 支出有文字；不推算缺失数据。',metrics([['本月支出','¥ 128.30'],['本月收入','¥ 320.00'],['结余','¥ 191.70']])+`<div class="control-actions">${button('添加交易','transaction')}${button('导入账单','bill')}</div>${table(['日期','说明','收支','分类','金额'],[['2026-10-08','演示午餐','支出','餐饮','¥ 12.30'],['2026-10-07','演示收入','收入','收入','¥ 320.00'],['2026-10-06','演示交通','支出','交通','¥ 8.50']])}`);
html+=section('bill-import','账单识别与确认预览','银行分列金额、微信、支付宝；确认后才写入。',panel('合成账单预览',`<p>识别 3 笔，跳过 1 行。请核对收支和分类。</p>${table(['日期','说明','收支','金额','来源'],[['2026-10-08','演示消费','支出','12.30','银行'],['2026-10-07','演示收入','收入','20.00','微信'],['2026-10-06','演示退款','收入','5.00','支付宝']])}<p class="preview-warning">非人民币及方向不明项目不会悄悄混入。</p><div class="control-actions">${button('取消预览')}${button('确认导入')}</div>`));
html+=section('prompts','提示词：分类、编辑、变量与建议','编辑器稳定；建议不自动覆盖原文。',`<div class="preview-editor-layout"><aside><h3>分类</h3><button>全部</button><button>写作</button><button>开发</button>${button('新增提示词')}</aside><article class="preview-panel"><h3>演示模板</h3><label class="control-field">标题<input value="整理一个主题"></label><label class="control-field">正文<textarea rows="6">围绕 {{topic}} 整理要点，输出 {{format}} 格式。</textarea></label><div class="control-actions">${button('预览变量','prompt-preview')}${button('优化建议','prompt-ai')}${button('评分建议','prompt-ai')}${button('保存提示词')}</div><p class="meta">演示建议不会连接 AI 服务或改写真实提示词。</p></article></div>`);
html+=section('skills','技能：只读扫描、筛选与详情','来源、启用与文件存在是不同状态。',`<div class="preview-filter-grid">${field('搜索技能','')}<label class="control-field">Agent<select><option>全部</option><option>Codex</option></select></label><label class="control-field">来源<select><option>已登记目录</option></select></label></div><div class="preview-demo-grid">${panel('演示技能','<span class="preview-badge">文件存在</span><p>整理工作资料的示例技能。</p><small>只读详情，不执行脚本。</small>'+button('查看技能','skill'))}${panel('来源状态','<p>扫描成功 · 2 个演示条目</p><p class="meta">不会扫描整盘或修改其他工具。</p>')}</div>`);
html+=section('settings','设置中心：全部栏目','个人资料、外观、AI、用量、数据、快捷键、关于。',`<div class="preview-settings-layout"><aside>${['个人资料','外观','AI 服务','用量与实验','数据与备份','快捷键','关于'].map(label=>`<a href="#${{'个人资料':'profile','外观':'appearance','AI 服务':'suppliers','用量与实验':'usage-settings','数据与备份':'backup','快捷键':'shortcuts','关于':'about'}[label]}">${label}</a>`).join('')}</aside>${panel('设置内容','<h3>只保存当前栏目</h3><p>右侧独立滚动，底部操作始终可达。</p>'+button('保存设置')+button('模拟保存失败','error'))}</div>`);
html+=section('appearance','外观与可编辑数值','主题、字号、亮度与减少动画；控件不重叠。',`<div class="preview-demo-grid">${panel('主题','<div class="control-actions"><button class="btn ghost" data-preview-theme>切换浅深主题</button></div><p>同一组业务状态在浅深主题中保持含义。</p>')}${panel('动画偏好','<label class="preview-task"><input type="checkbox" data-demo-reduced> 减少动态效果</label><p class="meta">保留进度与焦点，减少位移和持续弹性。</p>')}</div>`);
html+=section('suppliers','供应商、模型与多 Key','Key 显式保存，余额 / Token / 实际费用独立说明。',`<div class="control-actions">${button('添加供应商 Key','key')}</div>${table(['供应商','Key 名称','同步','能力','凭据'],[['演示供应商 A','个人 Key','已开启','Token / 费用','••••••••'],['演示供应商 B','备用 Key','未开启','余额','••••••••']])}${panel('编辑 Key',`<div class="preview-form-grid">${field('名称','演示 Key')}${field('供应商地址','https://example.invalid')}${field('模型','演示模型 A')}${field('API Key','demo-placeholder','password')}</div><div class="control-actions">${button('测试连接')}${button('取消')}${button('保存供应商 Key')}</div>`)}`);
html+=section('usage-settings','用量与实验设置','日志只读授权、工具独立、计价缺口保留。',`<div class="preview-demo-grid">${panel('来源监测',`${field('Codex 日志','演示日志目录')}${field('ZCode 日志','演示日志目录')}${field('Harness 日志','演示日志目录')}${button('保存采集设置')}`)}${panel('本机凭据',`<h3>授权读取本机 Codex 登录</h3><p>无内置官方登录 / 设备码。</p>${button('授权读取')}${button('撤销授权')}<p class="meta">日志统计和参考价值不随凭据变化。</p>`)}</div>`);
html+=section('backup','数据、加密备份与恢复','Profile 卡片共用；口令只用于当次操作。',`<div class="control-actions">${button('创建加密备份','backup')}${button('导出加密 Profile','backup')}</div>${table(['备份','范围','状态','操作'],[['演示备份','完整 Profile','已加密','下载 / 恢复']])}<div class="preview-demo-grid">${panel('资料位置','<p>演示 Profile / profile</p>'+button('切换 Profile','profile')+button('迁移资料','profile'))}${panel('空间与内存','<div class="preview-demo-donut storage-demo"><span>25.6 MiB<br><small>合成空间示例</small></span></div><ul class="preview-legend"><li>数据库　20 MiB</li><li>备份　4 MiB</li><li>浏览器　1.6 MiB</li></ul><p class="meta">分类互斥；内存缓存另列。</p>')}</div>`);
html+=section('prices','历史价格、汇率与核验依据','按日期查看，双币种与已核验部分明确。',`<div class="preview-filter-grid">${field('日期','2026-10-09','date')}${field('搜索模型','演示模型')}</div>${table(['模型','原币','输入 / 百万','缓存 / 百万','输出 / 百万','来源'],[['演示模型 A','USD','2.00','0.50','8.00','演示'],['演示模型 B','USD','--','--','--','缺价']])}<p class="preview-warning">这不是实际账单。缺价、缺分项和不明确的历史变价边界保持未知。</p>`);
html+=section('updates','更新详情与安装确认','检查 / 详情稳定占位，新版本以弹窗呈现。',panel('检查更新',`<div class="preview-update-row"><div><h3>检查更新</h3><p>手动确认下载与安装。</p><p class="lingxi-about-update-status">演示：发现新版本</p></div><div class="lingxi-update-actions">${button('检查更新','update')}${button('更新详情','update')}</div></div>`));
html+=section('shortcuts','快捷键与键盘操作','焦点、方向键、Esc 与草稿保护。',table(['操作','按键 / 控件','作用范围'],[['搜索与跳转','Ctrl + K','应用'],['侧栏收起 / 展开','Ctrl + B','应用'],['缩放重置','Ctrl + 0','应用'],['菜单 / 单选','方向键','当前控件'],['计价滑动','Home / End / 方向键','当前滑块'],['关闭 / 取消','Esc','当前弹层']]));
html+=section('toast','保存结果与 SwipeToast','真实组件；右下角；可滑走、可关闭、悬停暂停。',`<div class="control-actions">${button('个人资料已保存')}${button('供应商 Key 已添加')}${button('设置已保存')}${button('模拟失败通知','error')}</div><p class="meta">通知不阻挡表单，最多三条，不回显凭据。</p>`);
html+=section('motion','Logo 与状态动效','冷启动约 2 秒；Logo 不变；恢复窗口不重播。',`<div class="preview-splash" data-demo-splash><img src="assets/lingxi-logo.svg" alt="灵犀 Logo"><span>灵犀工作坊</span><small>Logo 出现、字标进入、短暂停留</small></div><div class="control-actions">${button('重播开屏','splash')}${button('重播额度入场','account')}</div>${table(['动作','时长','目的'],[['侧栏','300ms','横向伸缩，纵向稳定'],['主题','650ms','从控件中心展开'],['额度','800ms','首次真实结果入场'],['Credit','650ms','数字滚动出现'],['Logo 总时长','约 2000ms','冷启动一次']])}`);
html+=section('native','安装、卸载与托盘结构示意','原生未执行；这些示例不能当原生验收。',`<div class="preview-demo-grid">${panel('安装器',`<div class="onboarding-brand"><img src="assets/lingxi-logo.svg" alt="灵犀"><span>灵犀工作坊</span></div>${field('安装位置','演示安装目录')}${field('Profile 位置','演示安装目录 / profile')}<progress max="100" value="100"></progress><div class="control-actions">${button('立即启动')}${button('完成')}</div>`)}${panel('卸载与托盘','<p>程序已卸载，Profile 与个人资料保留。</p>'+button('完成卸载')+'<hr><p>桌面只显示一个托盘；网页版没有托盘。</p>'+button('从托盘恢复'))}</div>`);
html+=section('responsive','响应式与长内容','320 / 390px、字号 18px、125% 缩放与长名称。',`<div class="preview-demo-grid">${panel('长文本与数字','<p>这是一个较长的模型名称，用于确认换行与省略不遮挡主操作。</p><strong>9,223,372,036,854,775,807</strong><p class="meta">完整整数保留；图表尺度可近似，数据不能丢精度。</p>')}${panel('窄屏规则','<ul><li>根框架不横向挤压</li><li>卡片单列</li><li>表格在内部滚动</li><li>数值控件换行，不重叠</li><li>Toast 避让移动导航</li></ul>')}</div>`);
html+=section('accessibility','可访问性与演示边界','每个交互都有名称、焦点和等价操作。',`<div class="preview-demo-grid">${panel('键盘路径','<ol><li>Tab 进入输入或操作</li><li>方向键改变选项</li><li>Enter / Space 激活</li><li>Esc 关闭或取消</li><li>焦点返回原触发位置</li></ol>')}${panel('只读演示','<p>不读取真实账户，不保存 Profile，不连接供应商，不导入账单，不执行安装。</p><p>使用实际组件并展示合成状态；原生示意与协议模拟明确区分。</p>')}</div>`);
html+=section('about','关于、来源与许可证','一个统一入口，说明真实能力与边界。',D.about());
let dark=document.documentElement.dataset.theme==='dark';
document.getElementById('design-preview').innerHTML=`<header class="preview-top"><a class="preview-brand" href="index.html" data-preview-return><img src="assets/lingxi-logo.svg" alt="灵犀"><span>灵犀工作坊</span></a><span class="preview-demo-label">${__LINGXI_VERSION__} · 全站演示</span><div class="control-actions"><a href="index.html" data-preview-return>返回工作台</a><button type="button" class="btn ghost" data-preview-theme>${dark?'浅色':'深色'}预览</button></div></header><div class="preview-layout"><aside class="preview-toc"><h2>完整目录</h2><nav>${sections.map((s,i)=>`<a href="#${s.id}"><small>${String(i+1).padStart(2,'0')}</small>${e(s.title.split('：')[0])}</a>`).join('')}</nav></aside><main class="preview-content"><div class="preview-intro"><span class="preview-eyebrow">灵犀工作坊 · 设计系统</span><h1>每个界面都有明确的依据。</h1><p>从应用框架到局部状态，展示全部业务页面、设置栏目与实际控件。点击只改变演示，不连接真实 Profile。</p><div class="preview-index-facts"><span>${sections.length} 个展示章节</span><span>8 个业务模块</span><span>7 个设置栏目</span><span>浅深主题共用组件</span></div></div>${html}<footer>依据 design.md 维护 · 所有数值与资料均为合成演示 · 原生界面未执行 EXE 验收。</footer></main></div><div id="preview-toast"></div>`;
const q=s=>document.querySelector(s),notify=message=>R.toast(q('#preview-toast'),'演示：'+message);
window.workbenchRequest=async()=>{throw Error('设计预览不连接真实账户');};
function paintPalette(){q('[data-preview-theme]').textContent=(dark?'浅色':'深色')+'预览';document.querySelectorAll('[data-token-color]').forEach(node=>node.style.background=getComputedStyle(document.documentElement).getPropertyValue(node.dataset.tokenColor));document.querySelectorAll('[data-token-value]').forEach(node=>node.textContent=getComputedStyle(document.documentElement).getPropertyValue(node.dataset.tokenValue).trim());}
function setTheme(event){const trigger=event.currentTarget,rect=trigger.getBoundingClientRect(),x=rect.left+rect.width/2,y=rect.top+rect.height/2,paint=()=>{dark=!dark;document.documentElement.dataset.theme=dark?'dark':'light';history.replaceState(null,'',dark?'preview-dark.html':'preview.html');paintPalette();};if(document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const transition=document.startViewTransition(paint);transition.ready.then(()=>document.documentElement.animate({clipPath:[`circle(0 at ${x}px ${y}px)`,`circle(${Math.hypot(innerWidth,innerHeight)}px at ${x}px ${y}px)`]},{duration:650,easing:'cubic-bezier(.22,1,.36,1)',pseudoElement:'::view-transition-new(root)'})).catch(()=>{});}else paint();}
document.querySelectorAll('[data-preview-theme]').forEach(node=>node.onclick=setTheme);
try{const route=sessionStorage.getItem('lingxi-last-work-route');if(route&&/^#\/(overview|projects|summary|news|finance|usage|prompts|skills)/.test(route))document.querySelectorAll('[data-preview-return]').forEach(node=>node.href='index.html'+route);}catch{}
D.identity(q('[data-demo-identity]'),{name:'演示用户',save:async()=>notify('个人资料已保存，未写入实际 Profile')});
R.scrubField(q('[data-demo-font]'),{ariaLabel:'界面字号',value:14,min:12,max:18,step:2,onChange:v=>{document.documentElement.style.setProperty('--ui-font-size',v+'px');}});
R.scrubField(q('[data-demo-brightness]'),{ariaLabel:'界面亮度',value:100,min:85,max:110,step:1,onChange:v=>{q('[data-demo-brightness-value]').textContent=v+'% · 仅改变预览区域';q('#controls').style.filter='brightness('+v/100+')';}});
let checked=true;const switchPaint=()=>R.squishSwitch(q('[data-demo-switch]'),{checked,ariaLabel:'演示自动同步',onChange:value=>{checked=value;switchPaint();}});switchPaint();
let radioValue='daily';const radioPaint=()=>R.radio(q('[data-demo-radio]'),{items:[{value:'daily',label:'每日'},{value:'weekly',label:'每周'},{value:'all',label:'累计'}],value:radioValue,onChange:v=>{radioValue=v;radioPaint();}});radioPaint();
R.loader(q('[data-demo-loader]'),'演示等待');R.progress(q('[data-demo-progress]'),64);
let accountReady=false,valueEnabled=false;
function paintAccount(){q('[data-demo-quotas]').innerHTML=[['primary','5 小时额度',74.2,300],['secondary','每周额度',38.6,10080]].map(([slot,label,value,minutes])=>{let markup=quota(slot,label,accountReady?value:0,minutes);return accountReady?markup:markup.replace('data-quota-slot=','data-quota-known="false" data-quota-slot=').replace('0.0% 剩余','--').replace(/重置 [^<]+/,'重置 --');}).join('');q('[data-demo-quotas]').querySelectorAll('.quota-time').forEach(node=>node.setAttribute('stroke-dasharray',accountReady?'50 100':'0 100'));q('[data-demo-credit]').textContent=accountReady?'180.50':'--';q('[data-demo-account-state]').textContent=accountReady?'演示凭据已读取':'尚未读取';D.resetBatteries(q('[data-demo-batteries]'),accountReady?{availableCount:2,credits:[{grantedAt:Date.now()/1000-86400,expiresAt:Date.now()/1000+86400},{expiresAt:null}]}:null);}
function paintValue(){R.slideCommit(q('[data-demo-value-slide]'),{enabled:valueEnabled,compact:true,onConfirm:async()=>{valueEnabled=!valueEnabled;paintValue();return true;}});q('[data-demo-usd]').textContent=valueEnabled?'128.00':'--';q('[data-demo-cny]').textContent=valueEnabled?'896.00':'--';}
paintAccount();paintValue();paintPalette();C.mount(document);
function dialog(title,content,primary='确认'){const d=document.createElement('dialog');d.className='control-dialog preview-dialog';d.innerHTML=`<header class="control-dialog-head"><h3>${e(title)}</h3><button class="btn ghost" data-close aria-label="关闭">×</button></header><div class="preview-dialog-content">${content}</div><div class="control-dialog-actions"><button class="btn ghost" data-close>取消 / 返回</button><button class="btn" data-confirm>${e(primary)}</button></div>`;document.body.append(d);d.querySelectorAll('[data-close]').forEach(node=>node.onclick=()=>d.close());d.querySelector('[data-confirm]').onclick=()=>{notify(title+'已完成，未写入实际资料');d.close();};d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();}
const dialogs={project:['新增项目',field('项目名称','演示项目')+field('说明','准备本周工作')],task:['新增待办',field('标题','整理资料')+field('日期','2026-10-09','date')+field('地点','演示会议室')],notification:['通知识别预览','<label class="control-field">原文<textarea rows="3">演示通知：明天下午进行资料核对。</textarea></label>'+field('识别标题','资料核对')+field('日期','2026-10-10','date')],transaction:['添加交易',field('说明','演示交易')+field('金额','12.30','number')],bill:['账单确认','<p>3 笔合成交易，确认后只显示演示反馈。</p>'],key:['添加供应商 Key',field('名称','演示 Key')+field('API Key','demo-placeholder','password')],backup:['创建加密备份',field('备份口令','','password')+field('再次输入口令','','password')],profile:['选择 Profile','<div class="onboarding-cards"><article class="onboarding-card"><h3>当前演示 Profile</h3><p>保留工作内容。</p></article><article class="onboarding-card"><h3>另一个演示 Profile</h3><p>选择后不操作实际目录。</p></article></div>'],update:['发现新版本 · 演示','<h3>更新内容</h3><ul><li>界面稳定与完整设计规范</li><li>增量计算与安装包优化</li></ul><p>这个弹窗不下载或执行实际安装包。</p>'],skill:['技能详情','<h3>演示技能</h3><p>只读说明。</p><pre><code>SKILL.md · 示例内容</code></pre>'],'prompt-ai':['AI 建议','<p>这是合成建议，不调用模型。应用后只显示演示反馈。</p>'],'prompt-preview':['变量预览','<p>topic：演示主题；format：Markdown。</p>'],dialog:['标准弹窗','<p>统一标题、内容、错误和操作。</p>'+field('示例名称','演示') ]};
document.addEventListener('click',event=>{const target=event.target.closest('[data-demo-action]');if(!target)return;const action=target.dataset.demoAction;if(action==='sidebar'){const shell=q('[data-demo-shell]');shell.classList.toggle('preview-shell-collapsed');return;}if(action==='account'){accountReady=!accountReady;paintAccount();return;}if(action==='splash'){const node=q('[data-demo-splash]');node.classList.remove('playing');void node.offsetWidth;node.classList.add('playing');return;}if(action==='error'){notify('保存失败，请重试；演示输入保留');return;}if(dialogs[action])dialog(...dialogs[action],action==='update'?'下载安装（演示）':'确认（演示）');else notify(action+'，未改变实际资料');});
document.querySelectorAll('[data-demo-module]').forEach(node=>node.onclick=()=>{document.querySelectorAll('[data-demo-module]').forEach(item=>item.classList.toggle('selected',item===node));q('[data-demo-module-label]').textContent=node.dataset.demoModule;});
q('[data-demo-reduced]').onchange=event=>{document.documentElement.dataset.motion=event.target.checked?'reduced':'full';notify(event.target.checked?'已减少动画':'已恢复动画');};
q('[data-about-check-update]').onclick=()=>dialog(...dialogs.update,'下载安装（演示）');q('[data-update-details]').onclick=()=>dialog(...dialogs.update,'下载安装（演示）');q('[data-profile-switch]').onclick=()=>dialog(...dialogs.profile);
const observer=new IntersectionObserver(entries=>{const entry=entries.find(item=>item.isIntersecting);if(entry)document.querySelectorAll('.preview-toc a').forEach(node=>node.setAttribute('aria-current',node.hash==='#'+entry.target.id?'location':'false'));},{rootMargin:'-80px 0px -65% 0px'});document.querySelectorAll('[data-preview-section]').forEach(node=>observer.observe(node));
window.addEventListener('pagehide',()=>{observer.disconnect();C.dispose(document);R.cleanup();});
window.lingxiPreviewCoverage={version:__LINGXI_VERSION__,sections:sections.map(s=>s.id),businessModules:8,settingsSections:7,data:'synthetic-only'};
